name: my_app
description: A new Flutter project.
version: 1.0.0
environment:
  sdk: '>=2.14.0 <3.0.0' # Specify a valid Dart SDK version constraint
dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.0
  http: ^0.13.3
  flutter_svg: ^0.22.0 # Add the flutter_svg package
  cupertino_icons: ^1.0.2
  image_picker: ^0.7.0  # Replace with the latest version
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/sticky_note.png # Add this line to include your SVG asset
